### ISSUE TITLE
Discuss feature additions

### ISSUE THREAD

**Issue by coreyjs** [corey-rb/juliet#16]

**Comment by RudyB** [comment]
@corey-rb I am not quite sure what you are trying to accomplish with this issue. Are you wanting to create a discussion on what features users would want?

**Comment by coreyjs** [comment]
Yea, sorry for the confusion.  This is just to review and go over any feature ideas (there are better places for this I guess).  This project is new and it meant as a learning ground for learning Swift at a deeper level.
