### ISSUE TITLE
Logger Initialization

### ISSUE THREAD

**Issue by coreyjs** [corey-rb/juliet#17]
We need a simpler solution to the default initialization of the Logger.  We can probably get away with doing a Singleton implementation of this, and modify in the future if we get issues

**Comment by RudyB** [comment]
@corey-rb What would you want the configuration of the shared Singleton config to look like? Similar to the one in the readme? 
Ex: `Configuration(
                        logLevels: [.warning, .alert, .error, .noerror, .fatal], composer: .console)`?

**Comment by coreyjs** [comment]
I think the configuration initialization can stay how it is, but for now we make the `Logger` class its self a singleton.  This should alleviate the redundant initializations in every class that needs it.

This may change in the future, but for now im happy with this approach.

**Comment by RudyB** [comment]
Do you want to assign me the task? I want to give this a try

Thanks, Rudy Bermudez
On Fri, Oct 20, 2017 at 6:03 AM, Corey Schaf <notifications@github.com> wrote:
I think the configuration initialization can stay how it is, but for now we make the Logger class its self a singleton. This should alleviate the redundant initializations in every class that needs it.

This may change in the future, but for now im happy with this approach.

**Comment by coreyjs** [comment]
added you on as collaborator, so I can assign the task.

**Comment by RudyB** [comment]
The shared singleton in Logger requires an initial configuration. 

So I am proposing adding a singleton to Configuration
```swift
public static let defaultConfiguation: Configuration = Configuration()
```


Creating a singleton in Configuration allows me to access the private init method declared in the class.
```swift
private init() {
        self.levels =  [LogLevel.noerror, LogLevel.warning, LogLevel.alert, LogLevel.error, LogLevel.fatal]
        self.exportFormat = .json
        self.composerType = .console
    }
```

This means that the the Logger singleton can be initialized as so:
```swift
static let shared: Logger = Logger(configuration: Configuration.defaultConfiguation)
```

@corey-rb What are your thoughts on this?

**Comment by coreyjs** [comment]
Looks good to me
