### ISSUE TITLE
README finalization

### ISSUE THREAD

**Issue by coreyjs** [corey-rb/juliet#25]

**Comment by RudyB** [comment]
Are you going to update the readme to have the new initialization method?

**Comment by coreyjs** [comment]
Yep!  Plus a bunch more on how to properly use the different methods.  I have been slacking on it

**Comment by RudyB** [comment]
I want to commit to working on this project long term. Should we open a slack for it so that contributors can better communicate?

**Comment by coreyjs** [comment]
@RudyB yea great idea.

**Comment by coreyjs** [comment]
@RudyB a slack where we can discuss this as well as open ios/swift discussions would be nice.  What shall we name it?
